### ISSUE TITLE
Issues in Ubuntu POS print

### ISSUE THREAD

**Issue by gmoncada** [OpenPymeMx/ProxyPoS#15]
Hello, thanks for great module... i follow all the instructions, but i have this issue:

2015-01-10 18:12:35,555 - proxypos.proxypos.app - ERROR - Failed to print receipt
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/app.py", line 90, in do_print
    device.print_receipt(receipt)
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/controlers/printer.py", line 73, in print_receipt
    self._printImgFromFile(filename)
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/controlers/printer.py", line 225, in _printImgFromFile
    img = Image.open(filename).convert("1")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1955, in open
    fp = __builtin__.open(fp, "rb")
IOError: [Errno 2] No such file or directory: '/home/pos/.proxypos/templates/logo.jpg'

**Comment by agb80** [comment]
@gmoncada sorry for my late answer.

I saw you are using 1.2 version for ProxyPos. In that version receipt templates are still hardcoded into the code, you need to edit the function `print_receipt` (https://github.com/OpenPymeMx/ProxyPoS/blob/master/proxypos/proxypos/controlers/printer.py#L67) to match your needs. In this specific case, ProxyPoS is looking for a file named `logo.jpg` on folder `/home/pos/.proxypos/templates` to print your logo at the top of the receipt.

There are two short term options to solve this situation:
1. Put the logo file in place in order to ProxyPoS be able to read the file and print the entire receipt template
2. Open the file `printer.py` on your folder `/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/controlers/` and edit the print_receipt function to adjunts the template to your needs.

There is also a long term option to solve this issue:
- On branch `templates` we have been working on a system simplify the receipt template creation using a txt file for define the layout and printout but there are still some issues to solve before make a full release. If you would like to support the development we can help you to get a better software and support your production deployment and operation.

**Comment by gmoncada** [comment]
I really appreciate your response,
I 'll try some things in the receipt, please contact me, I want to support the development.

Best Regards

**Comment by agb80** [comment]
Github don't allow send private messages neither give me your contact information, please mail us to info[at]openpyme.mx for get in contact.

Thanks in advance!
