### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by sm2x** [OpenPymeMx/ProxyPoS#17]
hi, is this project still active?
is this same from the posbox project or different?
can you print in different languages, like chinese, arabic, etc.?

**Comment by agb80** [comment]
Yes, this project is alive, we have it in production with several customers and there are several WIP changes and improvements, but we use this repo just for publish finished work.

This project is totally different than posbox, even you can check that the creation date from this repo is lot of time before Odoo announce anything related to PosBox. We have been working on this project since late 2012.

I don't understand exactly what you mean by "print different languages", but let me tell you that ProxyPoS is able to print using any charset available on your pos printer.

**Comment by sm2x** [comment]
unlike in odoo v8 pos, you can set the IP of the proxy when you choose to print via proxy but in openerp v7 pos, all you can do is enable the print via proxy, my question is assuming i installed ProxyPoS on another host, how can the pos find it?

language, i mean if my receipt is in arabic, will it print correctly using ProxyPoS?

i read a couple of issues that are supposed to be fixed on 1.3 milestone, is 1.3 version
already available or the fixes are backported on the current repo?

thank you for your prompt reply.

**Comment by agb80** [comment]
You're right, the idea is that you install OpenERP in a server and you install ProxyPoS on every client box. The feature that allow to send the print data to a different box than the client box is not available on v7 but backporing is really simple.

We are native spanish and have a customer on Germany, we have being able to print on english, spanish and german with special characters on spanish and german without problems.

No, version 1.3 is not available on public domain yet, just for our customers.
