### ISSUE TITLE
Port Issues?

### ISSUE THREAD

**Issue by donmuri** [OpenPymeMx/ProxyPoS#3]
I followed the documentation but as I restarted my server, OpenERP failed to start as it clashes with the ProxyPOS port. For some reason, they share the same port? I tried changing OpenERP port number to 8068 and OpenERP can start as expected but the print result is still unclear.

I am using Linux Mint 13 Maya with OpenERP v7. The printer I am using is Partner RP320.

**Comment by agb80** [comment]
The driver is not thinking for use one the same machine where you have OpenERP server installed and also OpenERP javascript server is hardcoded on port 8069 for communicate with proxy devices. It's normal that if you install both on same computer you need to change port for one of them.

In order to track the error with your current installation I will ask you to follow this debut steps:
1.- Ensure that the PoS you are using has the "Print via Proxy" option enabled. Go to Point of Sales >> Configuration >> Point of Sales and edit your current PoS
2.- Enable Debug level on ProxyPoS configuration file and check log files for any error or message posted on there that could help us to locate the issue.

**Comment by donmuri** [comment]
With Print via Proxy enabled on OpenERP. nothing will be print out at all. 

I should allow both OpenERP and the ProxyPOS to run on the same port?

I will try your second solution to check whats the error.

**Comment by agb80** [comment]
Is not possible to run both apps on the same port. Let's going to wait for the log files to see what is happening.

**Comment by donmuri** [comment]
Hi there,

I have manage to fix the printer issues. I have a few questions on the 
possible limitations of ProxyPos.

Correct me if I am wrong, but how ProxyPos works is that it overrides 
OpenERP default receipt template for its own, ie printer.yaml? For 
example, you cannot automatically pull the company logo uploaded from 
OpenERP, you have to define the image path inside printer.yaml.

The print result is not properly aligned. It is align towards the left 
and there is a lot of space on the right side of the receipt. I have 
tried adjusting the width size at self.printer.pxWidth = 200 to 297, the 
proper size of the receipt but the result is still the same.

For some reason, the printer doesnt print out if I have more than one 
product on the receipt. It doesnt produce any error in the log.

Lastly, any news on the Windows XP fix?

Looking forward to your reply.

Happy new year and enjoy your holidays!

**Comment by agb80** [comment]
We are back from vacations and we are establishing a better time frame for respond your issues, thanks for your patine.

Regarding your questions: 

1.- Yes ProxyPos overrides the receipt template as the main purpose is to use it with a Internet remote server, so there is no way for OpenERP server to directly interact with PoS hardware.
2.- For company logo we have a way to pull from OpenERP database but implies patch OpenERP PoS module that's why is not published here
3.- Our fault, the pxWdith setting is for align the image printing. For control the character width on receipts we have added new parameters on printer.yaml file on develop branch. Please update and test.
4.- That has been corrected on develop and a master branches for now.
5.- This weekend we are going to work on the Windows XP fix.

**Comment by agb80** [comment]
Let me know if you are interested on the patched version of the PoS module.
